const CHAPTER = {
  CHAPTER_REQUEST: 'CHAPTER_REQUEST',
  CHAPTER_MESSAGES: 'CHAPTER_MESSAGES',
  CHAPTER_DETAILS: 'CHAPTER_DETAILS',
  CHAPTER_ERROR: 'CHAPTER_ERROR',
  CHAPTER_COMMENTS: 'CHAPTER_COMMENTS',
};

export default CHAPTER;
