const STORIES = {
  STORIES_REQUEST: 'STORIES_REQUEST',
  PUBLISHED_STORIES: 'PUBLISHED_STORIES',
  UNPUBLISHED_STORIES: 'UNPUBLISHED_STORIES',
  IN_REVIEW_STORIES: 'IN_REVIEW_STORIES',
  STORIES_ERROR: 'STORIES_ERROR',
  DRAFT_STORIES: 'DRAFT_STORIES',
  SINGLE_STORY: 'SINGLE_STORY',
  CHARACTER_DETAILS: 'CHARACTER_DETAILS',
  GENRE_STORIES: 'GENRE_STORIES',
  LOAD_MORE_PUBLISHED_STORIES: 'LOAD_MORE_PUBLISHED_STORIES',
  DROPDOWN_STATE: 'DROPDOWN_STATE',
  READING_SETTINGS: 'READING_SETTINGS',
};

export default STORIES;
